version: '2'
services:
    jenkins:
      image: 'jenkins/jenkins:lts'
      container_name: 'jenkins-master'
      ports:
        - '8080:8080'
        - '50000:50000'
      environment:
        - JENKINS_USERNAME=jenkins
        - JENKINS_PASSWORD=jenkins    
      volumes:
        - '/opt/jenkins-data:/var/jenkins_home/'
        
        
        
        
#############################################
#sudo docker run -u root --rm -d -p 8080:8080 -p 50000:50000 -v jenkins-data:/var/jenkins_home -v /var/run/docker.sock:/var/run/docker.sock --name jenkins-master jenkinsci/blueocean
#sudo docker exec -it jenkins-master bash
