version: '3.7'
services:
    jenkins:
      build:
        context: ./
        dockerfile: ./Dockerfile
      container_name: 'jenkins-master'
      restart: always
      ports:
        - '8080:8080'
        - '50000:50000'
      environment:
        - JENKINS_USERNAME=jenkins
        - JENKINS_PASSWORD=jenkins
      volumes:
        - '/var/jenkins-data:/var/jenkins_home/'

#############################################

FROM jenkins/jenkins:lts
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN /usr/local/bin/install-plugins.sh < /usr/share/jenkins/ref/plugins.txt

#############################################

ucumber-testresult-plugin:0.8.2
pam-auth:1.1
matrix-project:1.4.1
script-security:1.13

  
        
        
#############################################
sudo docker-compose -f docker-compose-jenkins.yaml up

#sudo docker exec -it jenkins-master bash

############################################
https://stackoverflow.com/questions/46255277/how-do-i-add-plugins-to-a-docker-jenkins
